# Generated by Django 5.1.1 on 2025-02-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurentname', models.CharField(max_length=120)),
                ('restaurentimage', models.TextField()),
                ('restaurentcusines', models.TextField()),
                ('restaurentopenig', models.TextField()),
                ('restaurantclosing', models.TextField()),
                ('restaurantaddress', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='Main_app.users')),
            ],
        ),
    ]
