# Generated by Django 5.1.1 on 2025-02-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=130)),
                ('itemdescription', models.TextField()),
                ('itemimage', models.TextField()),
                ('itemStyles', models.TextField()),
                ('itemprice', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='Admin_app.restaurents')),
            ],
        ),
    ]
