# Generated by Django 5.1.1 on 2025-02-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_menuitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='itemStyles',
            new_name='itemstyles',
        ),
    ]
