# Generated by Django 5.1.1 on 2025-02-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_rename_itemstyles_menuitems_itemstyles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='itemdiscount',
            field=models.FloatField(default=0.0),
        ),
    ]
